name = "b2"
main = "worker.ts"
compatibility_date = "2025-07-29"

routes = [{ pattern = "b2.hakula.xyz", custom_domain = true }]

[vars]
B2_HOSTNAME = "s3.us-west-004.backblazeb2.com"
UMAMI_ENDPOINT = "https://umami.hakula.xyz/api/send"
UMAMI_WEBSITE_ID = "f32be3f6-7de7-4061-bd0b-5077daa7a7e1"

[observability.logs]
enabled = true

[placement]
mode = "smart"
